### ISSUE TITLE
Dunkler Text auf dunklem Grund im Suchfeld im Darkmode

### ISSUE THREAD

**Issue by tomster** [ZeitOnline/zondocs_theme#6]
<img width="323" alt="Screenshot 2023-02-15 at 14 50 19" src="https://user-images.githubusercontent.com/59207/219045617-99de8d54-71f3-4962-8a9e-eccff073d041.png">

**Comment by stollero** [comment]
[Fixed](https://github.com/ZeitOnline/zondocs_theme/commit/f8fe8375baeefd3f08fe7ca8685db191d936382d)
